### PR TITLE
Adding deep learning packages

### PR DESCRIPTION
**Pull request by valentina-s**
Adding keras and tensorflow.

If they cause some trouble I can show them a runnung example on Kaggle, and it is not entirely necessary to run it on Jupyterhub.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@lsetiawan this is not possible in this env b/c of missing dependencies in `conda-forge`: `grpcio` and `keras 2.2.2`. I'm working on them now and they should be available by the end of the day.

**Comment by lsetiawan** [comment]
@ocefpaf Sounds good. We won't update the docker image, until it's resolved. Let me know how if I can assist you with anything. Thanks.

**Comment by ocefpaf** [comment]
> @ocefpaf Sounds good. We won't update the docker image, until it's resolved. Let me know how if I can assist you with anything. Thanks.

I'll let you know as soon as I finish the builds. (The worst case scenario we pull those from `pip` instead of `defaults`.)

**Comment by valentina-s** [comment]
I removed the defaults, sorry forgot to pull the latest version. Locally I was simply did:
conda install keras
conda update tensorflow 

(that brought tensorflow to the latest version)

I can try from the conda-forge channel, if that is better.

**Comment by ocefpaf** [comment]
> I can try from the conda-forge channel, if that is better.

If you could try an env that does not use `defaults` at all, even if that implies some packages downgrades, that would help. If not we should probably pull those dependencies from `pip` instead of `defaults`. The issue b/c `defaults` and `conda-forge` do not mix well together with latest `conda` and the chances of getting a broken env is high.

See https://github.com/conda/conda/issues/7656#ref-commit-6088fe5 for more info.

PS: to test that without defaults you would need to edit your `.condarc`, remove `defaults` and try an env like:

```yaml
name: data_mining
channels:
  - conda-forge
dependencies:
  - python=3.6
  - jupyter
  - scikit-learn
  - pandas
  - seaborn
  - dask
  - matplotlib
  - dask-ml
  - keras
  - tensorboard
  - tensorflow
```


and see if that works with your notebooks.

**Comment by ocefpaf** [comment]
env@valentina-s I was able to run one of your notebooks with the environment above, but the one that does not import `keras` and `tensorflow`, the other notebook seems to be incomplete. Can you test it with the modified env just to be sure we don't need the pinned versions?

I'm stuck at providing the tensorflow version you need b/c of another dependency:

https://github.com/conda-forge/staged-recipes/pull/6521

**Comment by valentina-s** [comment]
Keras 2.1.6 from conda forge seems to work fine. I tested it locally. Sorry, the notebooks are messy, but I tested the main runs. I specified the version of tensorflow, because when I installed it locally I was getting an old version, so I fixed it to 1.9.0.

**Comment by lsetiawan** [comment]
Thanks @ocefpaf :+1:

**Pull request merged**
